version: "3.9"

volumes:
  postgres: {}

services:
  django-service:
    container_name: django-service
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: on-failure
