name: CI

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker
        run: docker compose build django-service

      - name: Run isort
        run: docker compose run django-service poetry run isort apps/ --check

      - name: Run black
        run: docker compose run django-service poetry run black apps/ --check

      - name: Run flake8
        run: docker compose run django-service poetry run flake8

      - name: Run mypy
        run: docker compose run django-service poetry run mypy --config mypy.ini apps/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file
        env:
          DJANGO_TEST__ENV: ${{ secrets.DJANGO_TEST__ENV }}
        run: |
          touch .env.
          echo "$DJANGO_TEST__ENV" >> .env.

      - name: Build docker
        run: docker compose build django-service

      - name: Run tests
        run:  docker compose run django-service poetry run pytest --cov=apps --cov-fail-under=80 tests/ -n 4 &&
              docker compose run django-service poetry run pytest --cov=apps tests/ --cov-report=xml -n 4
